trino:
  target: dev
  outputs:
    dev:
      type: presto
      method: none
      user: admin
      password:
      catalog: postgresql
      host: localhost
      port: 8080
      schema: public
      threads: 1