version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_citiebike
    environment:
      POSTGRES_DB: db_citiebike
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "54321:5432"
    networks:
      - project_network

  dbt:
    image: fishtownanalytics/dbt:0.20.0
    container_name: dbt_citiebike
    command: ["dbt", "run"]
    depends_on:
      - postgres
    volumes:
      - ./dbt:/dbt
    networks:
      - project_network

  minio:
    hostname: minio
    image: 'quay.io/minio/minio:latest'
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ROOT_USER: minio_access_key
      MINIO_ROOT_PASSWORD: minio_secret_key
    command: server /data --console-address ":9001"
    networks:
      - trino-network

  trino:
    hostname: trino
    image: 'trinodb/trino:latest'
    ports:
      - '8080:8080'
    volumes:
      - ${PWD}/trino-etc:/etc/trino
    networks:
      - trino-network

  mariadb:
    hostname: mariadb
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db
    networks:
      - trino-network

  hive-metastore:
    hostname: hive-metastore
    build: .
    ports:
      - '9083:9083'
    volumes:
      - ${PWD}/hivedata:/user/hive
      - ${PWD}/conf/metastore-site.xml:/opt/apache-hive-metastore-3.1.3-bin/conf/metastore-site.xml
      - ${PWD}/conf/core-site.xml:/opt/hadoop-3.3.4/etc/hadoop/core-site.xml
    depends_on:
      - mariadb
    networks:
      - trino-network

networks:
  minionetwork:
    driver: bridge

  project_network:
    driver: bridge

  trino-network:
    driver: bridge

volumes:
  data:
    driver: local

  minio-data:
    driver: local
