version: '3.8'

services:
  postgres-dbt:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: bike_rental
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "54321:5432"
    networks:
      - project_network

networks:
  project_network:
    driver: bridge
    
volumes:
  data:
    driver: local