version: '3.8'

services:
  postgres-dbt:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: bike_rental
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "54321:5432"
    networks:
      - project_network

  jobmanager:
    image: apache/flink:1.14.0-scala_2.12-java11
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager

  taskmanager:
    image: apache/flink:1.14.0-scala_2.12-java11
    expose:
      - "6121"
    depends_on:
      - jobmanager
    command: taskmanager

networks:
  project_network:
    driver: bridge
    
volumes:
  data:
    driver: local