version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_citiebike
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:54321"
    networks:
      - project_network

  dbt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dbt_citiebike
    command: ["dbt", "run"]
    depends_on:
      - postgres
    volumes:
      - ./dbt:/dbt
    networks:
      - project_network

  minio:
    image: minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - minionetwork
    volumes:
      - 'data:/data'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio
      - MINIO_DEFAULT_BUCKETS=raw,trusted,refined

networks:
  minionetwork:
    driver: bridge

  project_network:
    driver: bridge

volumes:
    data:
        driver: local